# Terraform deployment of Azure resources

# Name
name: Terraform deploy to Azure

# Triggers
on:
  workflow_dispatch:

# Jobs
jobs:
  Terraform_validate:
    runs-on: ubuntu-latest
    steps:
      - name: terraform installation
        uses: hashicorp/setup-terraform@v2.0.3
      - name: terraform init
        run: terraform init
      - name: terraform validate
        run: terraform validate
  Terraform_deploy:
    runs-on: ubuntu-latest
    environment:
      name: Terraform
    steps:
      - name: terraform installation
        uses: hashicorp/setup-terraform@v2.0.3
      - name: terraform init
        run: terraform init
      - name: terraform plan
        run: terraform plan
      - name: terraform apply
        run: terraform apply
