# Terraform deployment of Azure resources

# Name
name: Terraform

# Triggers
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Terraform_jobs:
    runs-on: ubuntu-latest
    steps:
      # Terraform install
      - run: echo "This is Terraform install"
      # Terraform validate
      - run: echo "This is Terraform validate"
      # Terraform plan (to a plan output text file)
      - run: echo "This is Terraform plan"
      # Terraform apply after reviewer approves
      - run: echo "This is Terraform apply"
