# Terraform deployment of Azure resources

# Name
name: Terraform deploy to Azure

# Triggers
on:
  workflow_dispatch:

# Jobs
jobs:
  Terraform_preapply:
    runs-on: ubuntu-latest
    steps:
      - name: terraform installation
        uses: hashicorp/setup-terraform@v2.0.3
      - name: terraform validate
        run: terraform validate
      - name: terraform plan
        run: terraform plan
  Terraform_apply:
    runs-on: ubuntu-latest
    environment:
      name: 'Terraform'
    steps:
      - name: terraform apply
        run: terraform apply
