# Terraform deployment of Azure resources

# Name
name: Terraform

# Triggers
on:
  workflow_dispatch:

# Jobs
jobs:
  Terraform_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: terraform installation
        uses: hashicorp/setup-terraform@v2.0.3
      - name: terraform validate
        run: terraform validate
      - name: terraform plan
        run: terraform plan
      - name: terraform apply
        run: terraform apply
